<div class="cart">
    <div class="page-title title-buttons">
        <?php if(!$this->hasError()): ?>
        <ul class="checkout-types">
        <?php foreach ($this->getMethods('top_methods') as $method): ?>
            <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
            <li><?php echo $methodHtml; ?></li>
            <?php endif; ?>
        <?php endforeach; ?>
        </ul>
        <?php endif; ?>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php echo $this->getChildHtml('form_before') ?>
    <form action="<?php echo $this->getUrl('checkout/cart/updatePost') ?>" method="post">
        <fieldset>
            <table id="shopping-cart-table" class="data-table cart-table">
				<colgroup>
					<col class="col-one" />
					<col class="col-two" />
					<col class="col-three" />
					<col class="col-four" />
				</colgroup>

            <?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>
                <tfoot>
                    <tr>
                        <td>
                            <button type="submit" name="update_cart_action" value="update_qty" title="<?php echo $this->__('Update Shopping Cart'); ?>" class="button btn-update"><span><span><?php echo $this->__('Update Shopping Cart'); ?></span></span></button>
                            <!--[if lt IE 8]>
                            <input type="hidden" id="update_cart_action_container" />
                            <script type="text/javascript">
                            //<![CDATA[
                                Event.observe(window, 'load', function()
                                {
                                    // Internet Explorer (lt 8) does not support value attribute in button elements
                                    $emptyCartButton = $('empty_cart_button');
                                    $cartActionContainer = $('update_cart_action_container');
                                    if ($emptyCartButton && $cartActionContainer) {
                                        Event.observe($emptyCartButton, 'click', function()
                                        {
                                            $emptyCartButton.setAttribute('name', 'update_cart_action_temp');
                                            $cartActionContainer.setAttribute('name', 'update_cart_action');
                                            $cartActionContainer.setValue('empty_cart');
                                        });
                                    }

                                });
                            //]]>
                            </script>
                            <![endif]-->
						</td>

                        <td id="coupon-column">
							<?php echo $this->getChildHtml('coupon') ?>
                        </td>

                        <td colspan="2">
							<div class="totals">
								<?php echo $this->getChildHtml('currency_switcher') ?>
								<?php if (!$this->getIsVirtual()): echo $this->getChildHtml('shipping'); endif; ?>
								<?php echo $this->getChildHtml('totals'); ?>
								<?php if(!$this->hasError()): ?>
								<ul class="checkout-types">
								<?php foreach ($this->getMethods('methods') as $method): ?>
									<?php if ($methodHtml = $this->getMethodHtml($method)): ?>
									<li><?php echo $methodHtml; ?></li>
									<?php endif; ?>
								<?php endforeach; ?>
								</ul>
								<?php endif; ?>
							</div>
                        </td>
                    </tr>
                </tfoot>
                <tbody>
                <?php foreach($this->getItems() as $_item): ?>
                    <?php echo $this->getItemHtml($_item) ?>
                <?php endforeach ?>
                </tbody>
            </table>
            <script type="text/javascript">decorateTable('shopping-cart-table')</script>
        </fieldset>
    </form>
</div>
