<?php
$_item = $this->getItem();
$isVisibleProduct = $_item->getProduct()->isVisibleInSiteVisibility();
$canApplyMsrp = Mage::helper('catalog')->canApplyMsrp($_item->getProduct(), Mage_Catalog_Model_Product_Attribute_Source_Msrp_Type::TYPE_BEFORE_ORDER_CONFIRM);
?>

<tr>
	<td class="item-image">
		<a href="<?php echo $this->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getProductName()) ?>">
			<img src="<?php echo $this->helper('catalog/image')->init(Mage::getModel('catalog/product')->load($_item->getProductId()), 'small_image'); ?>" alt="<?php echo $_item->getName() ?>" />
		</a>
	</td>

    <td class="item-name">
        <h3>
			<a href="<?php echo $this->getProductUrl() ?>">
				<?php echo $this->htmlEscape($this->getProductName()) ?>
			</a>
        </h3>
    </td>

    <td class="item-qty">
        Antal <input name="cart[<?php echo $_item->getId() ?>][qty]" value="<?php echo $this->getQty() ?>" size="2" title="<?php echo $this->__('Qty') ?>" maxlength="12" />
		<img class="qty-subtract" src="<?php echo $this->getSkinUrl(); ?>img/cart-icon-subtract.png" />
		<img class="qty-add" src="<?php echo $this->getSkinUrl(); ?>img/cart-icon-add.png" />
    </td>

    <td class="item-price">
        <?php $_incl = $this->helper('checkout')->getSubtotalInclTax($_item); ?>

		<?php echo $this->helper('checkout')->formatPrice($_incl-$_item->getWeeeTaxRowDisposition()) ?>
    </td>
</tr>
