<div class="discount">
	<form id="discount-coupon-form" action="<?php echo $this->getUrl('checkout/cart/couponPost') ?>" method="post">
		<input type="hidden" name="remove" id="remove-coupone" value="0" />

		<div class="input-box">
			<input class="input-text" id="coupon_code" name="coupon_code" placeholder="<?php echo $this->__('Coupon code') ?>" value="<?php echo $this->htmlEscape($this->getCouponCode()) ?>" />
		</div>

		<div class="buttons-set">
			<button type="button" title="<?php echo $this->__('Apply Coupon') ?>" class="button" onclick="discountForm.submit(false)" value="<?php echo $this->__('Apply Coupon') ?>">
				<img src="<?php echo $this->getSkinUrl(); ?>img/cart-icon-update.png" />
			</button>

			<?php if(strlen($this->getCouponCode())): ?>
				<button type="button" title="<?php echo $this->__('Cancel Coupon') ?>" class="button" onclick="discountForm.submit(true)" value="<?php echo $this->__('Cancel Coupon') ?>">
					<img src="<?php echo $this->getSkinUrl(); ?>img/cart-icon-remove.png" />
				</button>
			<?php endif;?>
		</div>
	</form>
</div>

<script type="text/javascript">
//<![CDATA[
var discountForm = new VarienForm('discount-coupon-form');
discountForm.submit = function (isRemove) {
    if (isRemove) {
        $('coupon_code').removeClassName('required-entry');
        $('remove-coupone').value = "1";
    } else {
        $('coupon_code').addClassName('required-entry');
        $('remove-coupone').value = "0";
    }
    return VarienForm.prototype.submit.bind(discountForm)();
}
//]]>
</script>
